# Generated by Django 2.2.3 on 2019-07-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='url_campaign',
            new_name='campaign',
        ),
        migrations.RenameField(
            model_name='sms',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='sms',
            name='campaign_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sms',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sms',
            name='link_campaign',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sms',
            name='pic',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sms',
            name='sale_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sms',
            name='sms_status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sms',
            name='tracking_report',
            field=models.CharField(default='', max_length=50),
        ),
    ]
